name: browser_detect
version: 2.0.0
author: Dan Schultz <dan@mixbook.com>
description: A library that provides information about the user's web browser.
homepage: http://www.github.com/danschultz/browser_detect.dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0
